global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  
  - job_name: "substrate_node"
    scrape_interval: 5s
    static_configs:
      - targets: ["deoxys:9615"]
    
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]